name: Deploy Node.js Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  security-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run OWASP Dependency Check (Using Docker)
        run: |
          docker run --rm \
            -v $(pwd):/src \
            owasp/dependency-check \
            --project "CBT-Backend" --scan /src --format "ALL" --out security-reports/

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: OWASP-Dependency-Check-Report
          path: security-reports/

  deploy:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AWS_EC2_IP }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: |
            # Stop service if running
            sudo systemctl stop cbt-backend || true

            # Clone repo if not exists
            if [ ! -d "/home/ec2-user/CBT-Backend" ]; then
              git clone https://github.com/Bhavin2301/CBT-Backend.git /home/ec2-user/CBT-Backend
            fi

            # Pull latest changes
            cd /home/ec2-user/CBT-Backend
            git reset --hard
            git pull origin main

            # Install dependencies
            npm ci

            # Run build if script exists
            if jq -e '.scripts.build' package.json >/dev/null; then
              npm run build
            else
              echo "No build script found, skipping..."
            fi

            # Check if systemd service exists
            if [ ! -f "/etc/systemd/system/cbt-backend.service" ]; then
              echo "Error: Systemd service file missing. Please create it manually."
              exit 1
            fi

            # Restart the service
            sudo systemctl daemon-reload
            sudo systemctl start cbt-backend
            sudo systemctl enable cbt-backend
